FROM ubuntu:18.04

RUN apt update
RUN apt -y upgrade 

##### Tools

### Docker
RUN snap install docker

### Kubectl
RUN snap install kubectl

### VS Code
RUN snap install vscode

### Git Kraken
RUN snap install gitkraken


##### Cloud CLI's

### Gcloud
RUN snap install google-cloud-sdk